services:
  postgres:
    image: postgres:latest
    container_name: eventideRev_db
    environment:
      POSTGRES_DB: eventide
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: